### ISSUE TITLE
Optimization for cmdPrint(PrintType type)

### ISSUE THREAD

**Issue by Aditeya** [Aditeya/NineMensMorris#11]
It can use the static command to print out the board saving lines of code

**Comment by EltoCode** [comment]
I don't quite understand, elaborate? @Aditeya

**Comment by Aditeya** [comment]
Like you can call the static printBoard function within the non static code

So printBoard(this.board, type) within the non static function

**Comment by EltoCode** [comment]
Ok I'll look into it.

**Comment by EltoCode** [comment]
Yeah, ok, still have no idea what to do @Aditeya

**Comment by Aditeya** [comment]
```
public void cmdPrint(PrintType type) {
    cmdPrint(nmmBoard, type);
}
```

something like this. and maybe try if its possible for other functions

**Comment by EltoCode** [comment]
ohhh ok, hmmm yeah
