### ISSUE TITLE
[Networking] Source Code Lacks Comments

### ISSUE THREAD

**Issue by EltoCode** [Aditeya/NineMensMorris#12]
Comment your code, so is the wisdom of the grasshopper.

If you don't comment your code, the grasshopper will kill you in your sleep tonight.

**Comment by Aditeya** [comment]
@EltoCode Do I need to comment the demos?

**Comment by EltoCode** [comment]
Nah, They're not the final ver, so no need

**Comment by Aditeya** [comment]
@EltoCode added source for the new additions of code in commit 8afdfb963c8a997be998a04ef17dd5f9c10851a4, now pls help on issue #19 T_T

**Comment by EltoCode** [comment]
We'll get it done, don't you worry @Aditeya
