### ISSUE TITLE
[logic-networking] code blocking in NMMApplication

### ISSUE THREAD

**Issue by Aditeya** [Aditeya/NineMensMorris#24]
everytime button is pressed a new socket is created

**Comment by Aditeya** [comment]
https://www.daniweb.com/programming/software-development/threads/520369/javafx-server-client-program
https://blogs.oracle.com/jtc/javafx,-sockets-and-threading:-lessons-learned

networking has to be implemented in its own thread to fix the problem

**Comment by Aditeya** [comment]
Added gui networking thread functionality in commit 0d59310c1320b29dbaa8f2a943cfc41c942e4c06
Only thing left to do is figuring out how to send inputs, using the LinkedBlockingQueue, from the GUI.

**Comment by Aditeya** [comment]
https://stackoverflow.com/questions/2393179/streamcorruptedexception-invalid-type-code-ac

possible solution @EltoCode

**Comment by EltoCode** [comment]
> https://stackoverflow.com/questions/2393179/streamcorruptedexception-invalid-type-code-ac
> 
> possible solution @EltoCode

yeah, that's what I thought was happening too, that's why I suggested using [shundownInput/Output] (https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#shutdownInput()) once you were done using it the first time. But this other comment should also work

**Comment by EltoCode** [comment]
If both the above solutions do not work, then try passing the ObjectStreams as parameter along with the sockets
